### ISSUE TITLE
Dead links in documentation.

### ISSUE THREAD

**Issue by apostolos-geyer** [ziglang/www.ziglang.org#417]
The links to [master](https://ziglang.org/documentation/master/) and the [Zig Standard Library](https://ziglang.org/documentation/master/std/) are currently giving 404's.

<img width="283" alt="Screenshot 2024-10-13 at 11 05 39 AM" src="https://github.com/user-attachments/assets/a3a526ff-6df2-488a-b32f-80c2f5c99458">

**Comment by kristoff-it** [comment]
fixed in faab7e1bc77665cdbdfa83805315eced7aa750c3

**Comment by pyhedgehog** [comment]
![image](https://github.com/user-attachments/assets/f57c7c69-17e1-491e-a6ca-f7eb81743764)
Not completely fixed. :-(
